#ifndef RDPIE_CORE_H
#define RDPIE_CORE_H

// Generated by cbindgen. Do not edit by hand.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle returned to Swift.
 *
 * `RdpServer::run()`'s future is not `Send` — upstream holds an
 * `Rc<tokio::sync::Mutex<&mut RdpServer>>` across awaits — so it cannot be
 * handed to `Runtime::spawn`. Instead a dedicated thread owns the runtime and
 * drives the server with `block_on`, which carries no `Send` bound.
 */
typedef struct RdpieServer RdpieServer;

/**
 * Configuration passed across the ABI. All strings are NUL-terminated UTF-8
 * owned by the caller; they are copied before this function returns.
 */
typedef struct RdpieConfig {
  uint16_t port;
  uint16_t width;
  uint16_t height;
  const char *username;
  const char *password;
  const char *cert_pem_path;
  const char *key_pem_path;
} RdpieConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Start the RDP listener on a dedicated runtime.
 *
 * Returns a handle, or null if configuration was invalid. The caller owns the
 * handle and must release it with `rdpie_server_stop`.
 *
 * # Safety
 *
 * `config` must point to a valid `RdpieConfig` whose string fields are either
 * null or valid NUL-terminated UTF-8.
 */
struct RdpieServer *rdpie_server_start(const struct RdpieConfig *config);

/**
 * Submit one BGRA8888 frame. Never blocks.
 *
 * Returns 0 accepted, 1 accepted after dropping the oldest queued frame,
 * -1 on a closed session or invalid arguments.
 *
 * # Safety
 *
 * `server` must be a handle from `rdpie_server_start` that has not been
 * stopped. `data` must point to at least `len` readable bytes.
 */
int32_t rdpie_server_submit_frame(struct RdpieServer *server,
                                  uint16_t width,
                                  uint16_t height,
                                  uintptr_t stride,
                                  const uint8_t *data,
                                  uintptr_t len);

/**
 * Whether the connected client has finished EGFX/AVC420 capability
 * negotiation. Swift should submit H.264 via
 * `rdpie_server_submit_h264_frame` once this returns `true`, and fall back
 * to raw BGRA via `rdpie_server_submit_frame` otherwise — the two paths
 * coexist; this never disables the raw path.
 *
 * Returns `false` for a null handle.
 *
 * # Safety
 *
 * `server` must be a handle from `rdpie_server_start` that has not been
 * stopped, or null.
 */
bool rdpie_server_gfx_active(const struct RdpieServer *server);

/**
 * Submit one AVC420-encoded H.264 frame covering a single full-frame
 * region (`region_left`/`region_top`/`region_right`/`region_bottom` are
 * inclusive edges, matching MS-RDPEGFX). `data` must already be Annex-B
 * formatted (start-code-prefixed NAL units) — VideoToolbox's AVCC output
 * needs converting to Annex-B before calling this, which happens on the
 * Swift side, not here.
 *
 * Returns 0 on success, -1 on invalid arguments or a rejected frame
 * (channel not negotiated yet, backpressure, or an encoding failure).
 * Multi-region submission is not supported in this phase.
 *
 * # Safety
 *
 * `server` must be a handle from `rdpie_server_start` that has not been
 * stopped. `data` must point to at least `len` readable bytes.
 */
int32_t rdpie_server_submit_h264_frame(struct RdpieServer *server,
                                       const uint8_t *data,
                                       uintptr_t len,
                                       uint16_t region_left,
                                       uint16_t region_top,
                                       uint16_t region_right,
                                       uint16_t region_bottom,
                                       uint8_t quantization_parameter,
                                       uint32_t timestamp_ms);

/**
 * Stop the server and release the handle. Safe to call with null.
 *
 * # Safety
 *
 * `server` must be a handle from `rdpie_server_start`, and must not be used
 * again afterwards.
 */
void rdpie_server_stop(struct RdpieServer *server);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RDPIE_CORE_H */
